### ISSUE TITLE
getting issue while running node Query.js

### ISSUE THREAD

**Issue by potini3** [hyperledger/education#120]
I was getting error like this can any one help me this one is fabcar 

Store path:C:\Users\admin\fabric-samples\fabcar\hfc-key-store
(node:6016) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition
instead
Successfully loaded user1 from persistence
Query has completed, checking results
error from query =  { Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]
    at Object.exports.createStatusError (C:\Users\admin\fabric-samples\fabcar\node_modules\fabric-client\node_modules\grpc\src\common.js:87:15)
    at Object.onReceiveStatus (C:\Users\admin\fabric-samples\fabcar\node_modules\fabric-client\node_modules\grpc\src\client_interceptors.js:1188:28)
    at InterceptingListener._callNext (C:\Users\admin\fabric-samples\fabcar\node_modules\fabric-client\node_modules\grpc\src\client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (C:\Users\admin\fabric-samples\fabcar\node_modules\fabric-client\node_modules\grpc\src\client_interceptors.js:614:8)
    at callback (C:\Users\admin\fabric-samples\fabcar\node_modules\fabric-client\node_modules\grpc\src\client_interceptors.js:841:24)
  code: 2,
  metadata: Metadata { _internal_repr: {} },
  details: 'access denied: channel [mychannel] creator org [Org1MSP]' }

**Comment by vishal3152** [comment]
the user credentials are invalid

**Comment by potini3** [comment]
Hi Vishal,

How do I ressolve it. I believe it is taking my credentials from hfc-key-store directly. These values are created when I run registerUser.js

**Comment by vishal3152** [comment]
make sure that your connection profile client org is same user belongs to

**Comment by potini3** [comment]
Today I deleted my hfc-key-store and restarted the fabric ./startfabric.sh and I got this error in the end of the Script
Error: error getting endorser client for channel: endorser client failed to conn                                                                                                                ect to peer0.org1.example.com:7051: failed to create new connection: context dea                                                                                                                dline exceeded

But I proceed to  ./startfabric.sh node
It worked fine and I ran enrollAdmin and registerUser after that I ran
Node query.js I didn't get any errors but It did not get any response I got like this below how to resolve this

PS C:\Users\admin\fabric-samples\fabcar> node Query.js
Store path:C:\Users\admin\fabric-samples\fabcar\hfc-key-store
(node:6384) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition
instead
Successfully loaded user1 from persistence
Query has completed, checking results
Response is  []
