### ISSUE TITLE
node registerAdmin.js fails

### ISSUE THREAD

**Issue by francas** [hyperledger/education#64]
I am following the EDX course and get the error below when trying to run `node registerAdmin.js`. What am I doing wrong?

auridas@auridas-VirtualBox:~/Projects/education/LFS171x/fabric-material/tuna-app$ node registerAdmin.js
/home/auridas/Projects/education/LFS171x/fabric-material/tuna-app/node_modules/fabric-client/lib/Client.js:746
	async _createOrUpdateChannel(request, have_envelope) {
	      ^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/auridas/Projects/education/LFS171x/fabric-material/tuna-app/node_modules/fabric-client/index.js:25:18)

**Comment by DamianLikszo** [comment]
I have the same problem.

**Comment by deb21** [comment]
same issue . not working

**Comment by nathalie-ckc** [comment]
If you encounter problems in the course, it's always good to search the course Discussion forum to see if someone else found the solution.  That's how I found this post by Indiefire & using nvm to get node v8.9.0 worked for me: https://courses.edx.org/courses/course-v1:LinuxFoundationX+LFS171x+3T2017/discussion/forum/i4x-LinuxFoundationX-LFS171x-course-3T_2017/threads/5b472605c5264809bd00139c

I've got a bunch of other feedback I want to submit for Chapter 7 for the effort to improve the edX course material in the import-edx-content branch, so I'll suggest to add that info to the troubleshooting tips.

**Comment by vishal3152** [comment]
I had faced the same issue.  Here is a utility application that does the same with ease.
https://github.com/vishal3152/RegisterUser

**Comment by francas** [comment]
Thanks, installing node 8.9.0 worked for me as well.
